# GRUPA 1: Serwery Bazodanowe
[db_servers]
db_node_1 ansible_host=20.250.145.151 ansible_user=Domel

# GRUPA 2: Serwery Aplikacyjne
[app_servers]
app_node_1 ansible_host=20.203.251.211 ansible_user=Domel

# ZMIENNE
[db_servers:vars]
db_port=5432
env_type=development
